### ISSUE TITLE
First try

### ISSUE THREAD

**Issue by Darkomen78** [MagerValp/AutoDSNBI#1]
I change only some value, but when I try create new NBI I got this error :

./DSR10113.nbi/DeployStudioAssistantInfo.plist: file does not exist or is not readable or is not a regular file

Source image is a fresh 10.11.3 AutoDMG master

**Comment by andrew-cc** [comment]
@Darkomen78 Did you discover what the issue was? I’m getting this as well.

**Comment by andrew-cc** [comment]
Actually, I figured it out. This occurs when the `dest_dir` is a relative, rather than absolute, path, which causes `defaults` to write somewhere else and not to the specific file.
